# Generated by Django 4.2.9 on 2024-02-10 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetopause', '0004_alter_comment_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
    ]
