# Generated by Django 4.2.9 on 2024-01-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='favourite_quote',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='about',
            name='my_story',
            field=models.TextField(default='empty'),
        ),
        migrations.AddField(
            model_name='about',
            name='why_i_started',
            field=models.TextField(default='empty'),
        ),
        migrations.AlterField(
            model_name='about',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
