# Generated by Django 4.2.9 on 2024-02-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_favourite_quote_about_my_story_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('availability', models.TextField()),
                ('read', models.BooleanField(default=False)),
            ],
        ),
    ]
